#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("aTello.Resource", IsApplication=true)]

namespace aTello
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FFMpeg.Xamarin.Resource.String.ApplicationName = global::aTello.Resource.String.ApplicationName;
			global::FFMpeg.Xamarin.Resource.String.Hello = global::aTello.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int aTelloLogo2 = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int camera = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int DroneEye = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int eye = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int handlaunch = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int land = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int land_white = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int photogallery = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int placeholder = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int rec = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int record = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int settings_gear = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int takeoff = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int takeoff_hand = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int takeoff_white = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int takeoff_white2 = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int takepicture = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int xnewrth = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int xnewrth2 = 2130771986;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020002
			public const int batTextView = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cacheVideoSwitch = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int connectButton = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int convertAllVideoButton = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int convertVideoButton = 2130837510;
			
			// aapt resource value: 0x7F020000
			public const int DecoderView = 2130837504;
			
			// aapt resource value: 0x7F020007
			public const int decoderViewL = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int decoderViewR = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int exposureSpinner = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int galleryButton = 2130837514;
			
			// aapt resource value: 0x7F02000C
			public const int heiTextView = 2130837516;
			
			// aapt resource value: 0x7F02000B
			public const int hSpeedTextView = 2130837515;
			
			// aapt resource value: 0x7F02000D
			public const int iframeRateSpinner = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int joyLayout = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int joystickTypeSpinner = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int joystickViewL = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int joystickViewR = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int joystick_state = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int linearLayout1 = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int linearLayout3 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int linearLayoutLeft = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int linearLayoutRight = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int lookAtButton = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int lxSpinner = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int lySpinner = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int modeTextView = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int onScreenJoySwitch = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int photoQualitySwitch = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int picLayout = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int pictureButton = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int recLightButton = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int recordButton = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int relativeLayout1 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int rthButton = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int rxSpinner = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int rySpinner = 2130837540;
			
			// aapt resource value: 0x7F020001
			public const int SBSLayout = 2130837505;
			
			// aapt resource value: 0x7F020025
			public const int scrollView1 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int settingsButton = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int sharePhotoButton = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int space1 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int statusLayout = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int takeoffButton = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int textView1 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int textView2 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int throwTakeoffButton = 2130837549;
			
			// aapt resource value: 0x7F02002F
			public const int vbrSpinner = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int vbrTextView = 2130837552;
			
			// aapt resource value: 0x7F02002E
			public const int vSpeedTextView = 2130837550;
			
			// aapt resource value: 0x7F020031
			public const int wifiTextView = 2130837553;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Settings = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int connect_status = 2131034115;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7F050004
			public const int rec000000 = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int statusArea = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int statusArea2 = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
